# Aula 5 - Pizza Size

## Setup

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

## Carregando Dados

In [9]:
url = 'data/pizzasize.csv'
df = pd.read_csv(url)

display(df.head())
df.shape

   ID    Store CrustDescription        Topping  Diameter
0   1  Dominos      ThinNCrispy        Supreme     29.40
1   2  Dominos      ThinNCrispy  BBQMeatlovers     29.63
2   3  Dominos          DeepPan       Hawaiian     27.06
3   4  Dominos      ThinNCrispy        Supreme     27.45
4   5  Dominos     ClassicCrust       Hawaiian     26.59

(250, 5)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                250 non-null    int64
 1   Store             250 non-null    str
 2   CrustDescription  250 non-null    str
 3   Topping           250 non-null    str
 4   Diameter          250 non-null    float64
dtypes: float64(1), int64(1), str(3)
memory usage: 9.9 KB

In [20]:
df.describe().round(2)

           ID  Diameter
count  250.00    250.00
mean   125.97     28.31
std     72.94      1.28
min      1.00     25.51
25%     63.25     26.88
50%    125.50     28.76
75%    187.75     29.24
max    252.00     31.06